# Generated by Django 2.0.2 on 2018-09-13 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, help_text='Required. Letters, digits and @/#/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w@#-_]+$')], verbose_name='value')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
    ]
